### ISSUE TITLE
About the MIMIC dataset

### ISSUE THREAD

**Issue by ZechenZed** [lirus7/PPG-BP-Analysis#1]
Hi,

I read your paper and find out it is super helpful and inspiring. I actually got access to MIMIC III & IV and have already looked into them for a while. In your paper, you mentioned some similar PPG waveforms that have pretty different Systolic BP, but I did not see anything about PPG signals for now in MIMIC datasets III and IV. Could you help me find out which did you use since I may miss it? Thanks in advance!

Best regards,
Zechen Zhang

**Comment by lirus7** [comment]
Hey!
Thanks for your interest in our work. 

We did not download the complete MIMIC-III or MIMIC-IV datasets but did our analysis on a pre-processed [subset](https://archive-beta.ics.uci.edu/dataset/340/cuff+less+blood+pressure+estimation) of records but the analysis should translate to the bigger datasets too.

I would like to know few things:-
1. Did you pre-process the dataset? Usually the PPG signals have a certain trend that needs to be cleaned via a centering/detrend filter and some additional filters to get rid of noise.
2. You can play around with the filtering threshold to filter multivalued mappings. 

Please feel free to post your questions in this thread.
